Patientmodel
alexiscordts/sdmay21-44 pull request #41
Opened 2021-03-11 21:05 UTC by alexiscordts

Lets try this again....Refactored to database

2021-03-12 04:16 UTC, NgoTimothy commented on .vs/VSWorkspaceState.json
> +}
Do we need to check in this file?

2021-03-12 04:16 UTC, NgoTimothy commented on C#Backend/InpatientTherapySchedulingProgram/Controllers/PatientController.cs
> +}
Need newline at end of file

2021-03-12 04:21 UTC, NgoTimothy requested changes

2021-03-12 04:21 UTC, NgoTimothy commented on C#Backend/InpatientTherapySchedulingProgram/Models/Patient.cs
> +            return this.PatientId == patient.PatientId && this.FirstName == patient.FirstName && this.MiddleName == patient.MiddleName &&
When comparing strings, I think we need to do string1.Equals(string2) to compare the values and not just the reference.

2021-03-12 04:21 UTC, NgoTimothy commented on C#Backend/InpatientTherapySchedulingProgram/Services/PatientService.cs
> +        private bool PatientExists(int pid)
Can we turn this into an async method to get better concurrency?

2021-03-16 19:49 UTC, alexiscordts commented on C#Backend/InpatientTherapySchedulingProgram/Controllers/PatientController.cs
> +}
What do you mean??

2021-03-16 22:52 UTC, NgoTimothy approved these changes

2021-03-19 20:55 UTC, LucasKnoll approved these changes

2021-03-23 21:46 UTC, merged